
spring.application.name=TaskBrain
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/TaskBrain
spring.datasource.username=postgres
spring.datasource.password=dineshgk@2006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.org.hibernate.jpa.internal.util.LogHelper=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.springframework=INFO
