spring.application.name=TaskBrain
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/taskbrain
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# H2 Database Configuration (For Development/Testing)
# spring.datasource.url=jdbc:h2:mem:taskbrain;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.connections.pooling=ERROR
logging.level.org.hibernate.jpa.internal.util.LogHelper=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.springframework=INFO

# Email Verification (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kumar235376@gmail.com
spring.mail.password=${MAIL_PASSWORD:dummy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=${JWT_SECRET:veryLongSecretKeyForJwtAuthenticationRequiredToRunTheApplication123}

# AI Configuration
gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models/
gemini.model=gemini-flash-latest
